server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ride-service
          uri: lb://RIDE-SERVICE
          predicates:
            - Path=/rides/**
          filters:
            - StripPrefix=1

        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/drivers/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
