server:
  port: 8084

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:http://config-server:8888

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

    deserialization:
      trusted-packages: "*"

    listener:
      simple:
        default-requeue-rejected: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    prefer-ip-address: true
